### ISSUE TITLE
Content generation requires unusual address format.

### ISSUE THREAD

**Issue by MTecknology** [recoverysource/hugo-website#1]
The logic in ``generate_content.py`` requires the address to have a comma prior to the zip code. This is both non-standard and very limited.

```
Run make
python3 ./themes/aamod/generate_content.py
Traceback (most recent call last):
  File "./themes/aamod/generate_content.py", line 641, in <module>
    main()
  File "./themes/aamod/generate_content.py", line 44, in main
    gen_meeting_json(meetings)
  File "./themes/aamod/generate_content.py", line 200, in gen_meeting_json
    'postal_code': address[3].strip(),
IndexError: list index out of range
make: *** [Makefile:17: gen_content] Error 1
Error: Process completed with exit code 2.
```

**Comment by MTecknology** [comment]
After taking a closer look, the logic for address/city/state/zip is too deeply ingrained in the "meeting guide" application to trivially break apart this logic without creating new assumptions. The current design simply breaks each element into a comma-separated list, where each element can be populated or empty. The current situation already appears to be the current best solutions.

**Comment by MTecknology** [comment]
On tertiary thought, this really is an issue that has to be solved. It may be possible that the "best" solution is to drop the separate pages and turn them into a searchable form. Something like TSML-UI may be worth inspecting for some ideas for how this issue can be approached.

**Comment by MTecknology** [comment]
Note: https://github.com/recoverysource/aamod/issues/1

**Comment by MTecknology** [comment]
This is now cleaned up as much as possible. The 3-comma format is required for ``meeting-guide.html``, but any other place will just use the position of last comma without depending on int/str/etc. Any further refinement should focus on specific improvements/problems (separate issue).
